[tools]
"pipx:qmk" = "latest"

[tasks.sync-submodules]
run = '''git submodule update --init --recursive'''

[tasks.setup-lsp]
# install bear for this to work: https://github.com/rizsotto/Bear
run = ["make clean", "bear -- qmk compile"]
